import './globals.css';
import { Audiowide } from 'next/font/google'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const audiowide = Audiowide({ subsets: ['latin'], weight: "400"})
export default function RootLayout({ children }) {
	return (
		<html data-theme="aqua" className={audiowide.className}>
			<body>
			{children}
			</body>
		</html>
	);
}
